apiVersion: apps/v1
kind: Deployment
metadata:
  name: isis-4
spec:
  selector:
    matchLabels:
      app: isis-4-label
  replicas: 2
  template:
    metadata:
      labels:
        app: isis-4-label
    spec:
      containers:
        - name: isis4-web
          image: dmitrytretiakov/lab4:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "50m"
              memory: "1000Mi"
            limits:
              cpu: "100m"
              memory: "2000Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            failureThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 1
            initialDelaySeconds: 5
